import type { MathTopicConfig } from '@mathmagic/types';

export const CURRICULUM_TOPICS: MathTopicConfig[] = [
  // ── Grade 1 ──────────────────────────────────────────────────────────────────
  {
    id: 'g1_numbers_1_20',
    name: 'Numbers 1–20',
    icon: '🔢',
    grade: 1,
    color: '#4CAF50',
    description: 'Recognizing, reading, writing, and ordering numbers; counting forward/backward',
    difficulty: {
      easy: 'Numbers up to 10; identify or order a single number.',
      medium: 'Numbers up to 20; compare or order 2–3 numbers.',
      hard: 'Numbers up to 100; complete a sequence with a missing term.',
    },
  },
  {
    id: 'g1_addition',
    name: 'Addition up to 20',
    icon: '➕',
    grade: 1,
    color: '#F44336',
    description: 'Basic addition including making 10 and counting on',
    difficulty: {
      easy: 'Simple addition within 10, no regrouping (e.g., 3 + 4 = ?).',
      medium: 'Addition within 20, with regrouping (e.g., 7 + 8 = ?).',
      hard: 'Missing addend within 20 (e.g., 6 + ? = 14); multi-step addition word problem.',
    },
    expressionFor: ['easy', 'medium', 'hard'],
  },
  {
    id: 'g1_subtraction',
    name: 'Subtraction up to 20',
    icon: '➖',
    grade: 1,
    color: '#FF7043',
    description: 'Basic subtraction including counting back and finding the difference',
    difficulty: {
      easy: 'Simple subtraction within 10, no borrowing (e.g., 7 − 3 = ?).',
      medium: 'Subtraction within 20, with borrowing (e.g., 15 − 8 = ?).',
      hard: 'Missing minuend or subtrahend within 20 (e.g., ? − 5 = 9); multi-step subtraction word problem.',
    },
    expressionFor: ['easy', 'medium', 'hard'],
  },
  {
    id: 'g1_odd_even',
    name: 'Odd & Even Numbers',
    icon: '🔄',
    grade: 1,
    color: '#9C27B0',
    description: 'Identifying odd and even numbers; recognizing simple parity patterns',
    difficulty: {
      easy: 'Classify a single number as odd or even.',
      medium: 'Count how many odd or even numbers exist within a range.',
      hard: 'Reason about parity in a real-world sharing context.',
    },
  },
  {
    id: 'g1_place_value',
    name: 'Place Value (Ones & Tens)',
    icon: '🏛️',
    grade: 1,
    color: '#FF9800',
    description: 'Understanding two-digit numbers as tens and ones; composing and decomposing',
    difficulty: {
      easy: 'Identify the tens or ones digit in a two-digit number.',
      medium: 'Compose or decompose a two-digit number into tens and ones.',
      hard: 'Recognise equivalent representations of a two-digit number.',
    },
  },
  {
    id: 'g1_word_problems',
    name: 'Word Problems',
    icon: '📖',
    grade: 1,
    color: '#2196F3',
    description: 'Single-step problems involving altogether, how many left, or comparing',
    difficulty: {
      easy: 'Simple "add together" with very small numbers (within 5).',
      medium: '"How many left" subtraction within 15.',
      hard: '"Find the difference" comparison between two quantities within 20.',
    },
  },
  {
    id: 'g1_2d_shapes',
    name: '2D Shapes',
    icon: '🔷',
    grade: 1,
    color: '#E91E63',
    description: 'Recognizing and naming basic shapes; identifying vertices, sides, and corners',
    difficulty: {
      easy: 'Name a shape when given a picture or description.',
      medium: 'Count sides or vertices of a named polygon.',
      hard: 'Identify a shape from a list of properties (side lengths, corners).',
    },
  },
  {
    id: 'g1_time_clock',
    name: 'Time & Clock',
    icon: '⏰',
    grade: 1,
    color: '#607D8B',
    description: 'Reading and interpreting clocks at whole and half hours',
    difficulty: {
      easy: 'Read a clock showing a whole hour.',
      medium: 'Calculate the duration between two given times in whole hours.',
      hard: 'Read a clock showing a half hour; calculate the duration between two given times including half hours.',
    },
  },

  // ── Grade 2 ──────────────────────────────────────────────────────────────────
  {
    id: 'g2_natural_numbers_1000',
    name: 'Natural Numbers up to 1,000',
    icon: '🔢',
    grade: 2,
    color: '#4CAF50',
    description: 'Reading, writing, comparing, and ordering numbers up to 1,000',
    difficulty: {
      easy: 'Compare two two-digit numbers.',
      medium: 'Order three three-digit numbers from smallest to largest.',
      hard: 'Identify a number from its hundreds, tens, and ones place values.',
    },
  },
  {
    id: 'g2_addition_subtraction',
    name: 'Addition & Subtraction up to 1,000',
    icon: '➕',
    grade: 2,
    color: '#F44336',
    description: 'Vertical and mental calculation including regrouping, up to 1,000',
    difficulty: {
      easy: 'Two-digit addition within 100, no regrouping.',
      medium: 'Two-digit addition with regrouping.',
      hard: 'Two-step problem within 1,000 (add then subtract or vice versa).',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g2_multiplication_intro',
    name: 'Introduction to Multiplication',
    icon: '✖️',
    grade: 2,
    color: '#2196F3',
    description: 'Multiplication as repeated addition and as rectangular arrays',
    difficulty: {
      easy: '×2, ×5, ×10 facts presented as equal groups.',
      medium: 'Other single-digit times-table facts (×3, ×4, ×6).',
      hard: 'Missing factor problem within single-digit tables.',
    },
    expressionFor: ['easy', 'medium', 'hard'],
  },
  {
    id: 'g2_division_intro',
    name: 'Introduction to Division',
    icon: '➗',
    grade: 2,
    color: '#FF9800',
    description: 'Division as inverse of multiplication and as fair sharing',
    difficulty: {
      easy: 'Simple equal-sharing within ×2/×5 tables.',
      medium: 'Find the number of equal groups within ×3/×4 tables.',
      hard: 'Word problem requiring interpretation of a division situation.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g2_word_problems',
    name: 'Word Problems',
    icon: '📖',
    grade: 2,
    color: '#9C27B0',
    description: 'Multi-step word problems combining addition, subtraction, and multiplication',
    difficulty: {
      easy: 'One-step addition within 20.',
      medium: 'One-step multiplication context (equal groups).',
      hard: 'Two-step problem combining two different operations.',
    },
  },
  {
    id: 'g2_geometry_polygons',
    name: 'Geometry – 3D Bodies & Shapes',
    icon: '📦',
    grade: 2,
    color: '#E91E63',
    description:
      'Recognizing and naming 3D bodies (cube, box, cylinder, pyramid, cone); identifying vertices, sides, and faces; matching bodies to drawings or photographs',
    difficulty: {
      easy: 'Name a 3D body (cube, box, cylinder, pyramid, cone) from a picture or description.',
      medium: 'Identify the number of vertices, sides (edges), or faces of a named 3D body.',
      hard: 'Compare two 3D bodies and describe a similarity or difference between them.',
    },
  },
  {
    id: 'g2_time_clock',
    name: 'Time & Clock',
    icon: '⏰',
    grade: 2,
    color: '#607D8B',
    description: 'Reading and interpreting clocks at half and quarter hours; calculating durations',
    difficulty: {
      easy: 'Read a clock showing a half or quarter hour.',
      medium: 'Calculate the hour given a start time and duration in hours and half hours.',
      hard: 'Calculate the duration between two given times in half or quarter hours.',
    },
  },
  {
    id: 'g2_patterns',
    name: 'Patterns & Sequences',
    icon: '🔁',
    grade: 2,
    color: '#00BCD4',
    description: 'Identifying, continuing, and creating numerical patterns',
    difficulty: {
      easy: 'Continue a skip-counting sequence (by 2s).',
      medium: 'Continue a skip-counting sequence (by 5s).',
      hard: 'Fill in two missing terms in the middle of a sequence.',
    },
  },

  // ── Grade 3 ──────────────────────────────────────────────────────────────────
  {
    id: 'g3_natural_numbers_10000',
    name: 'Natural Numbers up to 10,000',
    icon: '🔢',
    grade: 3,
    color: '#4CAF50',
    description: 'Reading, writing, comparing 4-digit numbers; place value with thousands',
    difficulty: {
      easy: 'Write a 4-digit number in words or write it in digits given a number in words.',
      medium: 'Form the largest possible 4-digit number from given digits.',
      hard: 'Compare two 4-digit numbers.',
    },
  },
  {
    id: 'g3_addition_subtraction',
    name: 'Addition & Subtraction up to 10,000',
    icon: '➕',
    grade: 3,
    color: '#F44336',
    description:
      'Written and mental addition and subtraction of 4-digit numbers, including regrouping',
    difficulty: {
      easy: 'Add or subtract two 3-digit numbers, no regrouping.',
      medium: 'Add or subtract two 4-digit numbers with regrouping.',
      hard: 'Two-step problem within 10,000 (add then subtract or vice versa).',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g3_multiplication_table',
    name: 'Multiplication Table & Vertical Multiplication',
    icon: '✖️',
    grade: 3,
    color: '#2196F3',
    description: 'Mastery of all multiplication facts up to 10×10; 2-digit × 1-digit vertical',
    difficulty: {
      easy: 'Single multiplication fact within the 10×10 table.',
      medium: '2-digit or 3-digit × 1-digit vertical multiplication.',
      hard: 'Find the missing digit in a 2-digit × 1-digit product.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g3_division_remainder',
    name: 'Division with Remainder',
    icon: '➗',
    grade: 3,
    color: '#FF9800',
    description: 'Division within tables, with and without remainder',
    difficulty: {
      easy: 'Exact division fact within the 10×10 table.',
      medium: 'Division with a remainder; state quotient and remainder.',
      hard: 'Word problem where the remainder must be interpreted (e.g., rounding up cars).',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g3_order_of_operations',
    name: 'Order of Operations',
    icon: '🧮',
    grade: 3,
    color: '#795548',
    description: 'Correct order of operations, including parentheses',
    difficulty: {
      easy: 'Two operations, no parentheses (multiplication before addition).',
      medium: 'Expression with parentheses.',
      hard: 'Translate a word description into the correct expression.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g3_simple_fractions',
    name: 'Introduction to Fractions',
    icon: '🍕',
    grade: 3,
    color: '#9C27B0',
    description: 'Basic fractions (half, third, quarter, fifth) as parts of a whole or quantity',
    difficulty: {
      easy: 'Identify a fraction from a picture showing equal parts.',
      medium: 'Compare two unit fractions (e.g., 1/2 vs 1/3).',
      hard: 'Find a unit fraction of a quantity (e.g., 1/4 of 20).',
    },
    expressionFor: ['hard'],
  },
  {
    id: 'g3_two_step_word_problems',
    name: 'Two-Step Word Problems',
    icon: '📖',
    grade: 3,
    color: '#F44336',
    description: 'Problems requiring two calculation steps; emphasis on identifying the steps',
    difficulty: {
      easy: 'Same operation twice (add two equal amounts for two days).',
      medium: 'Two different operations (multiply then subtract).',
      hard: 'Multi-step with reasoning backward (work out an unknown component).',
    },
  },
  {
    id: 'g3_measurement_units',
    name: 'Measurement – Units & Conversion',
    icon: '📏',
    grade: 3,
    color: '#607D8B',
    description: 'Measuring with appropriate units; converting between standard units',
    difficulty: {
      easy: 'State the number of grams in 1 kg or cm in 1 m.',
      medium: 'Convert between units (e.g., 3.5 m to cm).',
      hard: 'Word problem involving measurement with conversion.',
    },
  },

  // ── Grade 4 ──────────────────────────────────────────────────────────────────
  {
    id: 'g4_large_numbers',
    name: 'Natural Numbers up to 1,000,000',
    icon: '🔢',
    grade: 4,
    color: '#4CAF50',
    description: 'Reading, writing, comparing, and rounding large numbers',
    difficulty: {
      easy: 'Write a 6-digit number from its word form.',
      medium: 'Round a 6-digit number to the nearest thousand.',
      hard: 'Estimate a sum of two large numbers to the nearest 10,000.',
    },
  },
  {
    id: 'g4_addition_subtraction',
    name: 'Addition & Subtraction',
    icon: '➕',
    grade: 4,
    color: '#F44336',
    description:
      'Written and mental addition and subtraction of multi-digit numbers without an upper limit',
    difficulty: {
      easy: 'Add or subtract two 4-digit numbers with regrouping.',
      medium: 'Add or subtract two large numbers (5–6 digits) with regrouping.',
      hard: 'Multi-step problem combining addition and subtraction of large numbers.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g4_long_multiplication_division',
    name: 'Long Multiplication & Division',
    icon: '✖️',
    grade: 4,
    color: '#2196F3',
    description:
      'Vertical multiplication with multi-digit factors; long division with 1- or 2-digit divisors',
    difficulty: {
      easy: '3-digit × 1-digit multiplication.',
      medium: '3-digit × 2-digit multiplication.',
      hard: 'Long division by a 2-digit divisor (exact).',
    },
    expressionFor: ['easy', 'medium', 'hard'],
  },
  {
    id: 'g4_fractions_extended',
    name: 'Fractions – Extended Understanding',
    icon: '🍕',
    grade: 4,
    color: '#9C27B0',
    description: 'Equivalent fractions, comparing fractions, fractions greater than 1',
    difficulty: {
      easy: 'Determine whether two fractions are equivalent.',
      medium: 'Compare two fractions with different denominators.',
      hard: 'Adding and subtracting mixed numbers when the denominators are equal or close',
    },
    expressionFor: ['hard'],
  },
  {
    id: 'g4_order_of_operations_advanced',
    name: 'Order of Operations (Advanced)',
    icon: '🧮',
    grade: 4,
    color: '#FF9800',
    description:
      'Solving multi-step expressions following the conventional order, with parentheses',
    difficulty: {
      easy: 'Two operations — multiplication before addition.',
      medium: 'Multiple operations with parentheses.',
      hard: 'Translate a multi-step word problem into the correct expression and solve it.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g4_prime_composite_numbers',
    name: 'Prime & Composite Numbers',
    icon: '🔢',
    grade: 4,
    color: '#9C27B0',
    description:
      'Identifying prime and composite numbers; understanding divisibility and number properties',
    difficulty: {
      easy: 'Identify whether a small number (up to 20) is prime or composite.',
      medium: 'Identify whether a larger number (up to 100) is prime or composite.',
      hard: 'List all prime numbers in a given range or find all factors of a composite number.',
    },
  },
  {
    id: 'g4_perimeter_area',
    name: 'Geometry – Perimeter & Area',
    icon: '📐',
    grade: 4,
    color: '#E91E63',
    description: 'Perimeter and area of rectangles, squares, right triangles',
    difficulty: {
      easy: 'Calculate the perimeter of a rectangle, square, or right triangle.',
      medium: 'Calculate the area of a rectangle, square, or right triangle.',
      hard: 'Find a missing side length given the area and one dimension.',
    },
  },
  {
    id: 'g4_multi_step_word_problems',
    name: 'Multi-Step Word Problems & Data',
    icon: '📖',
    grade: 4,
    color: '#F44336',
    description: 'Multi-step problems combining operations; reading double bar graphs and tables',
    difficulty: {
      easy: 'Two clear steps (e.g: multiply two prices then add totals).',
      medium: 'Three or more steps involving a fraction.',
      hard: 'Rate-based reasoning (pages per day, distance at speed).',
    },
  },

  // ── Grade 5 ──────────────────────────────────────────────────────────────────
  {
    id: 'g5_fractions_operations',
    name: 'Fractions – Addition & Subtraction',
    icon: '🍕',
    grade: 5,
    color: '#9C27B0',
    description:
      'Equivalent/reduced fractions; adding and subtracting with same and different denominators; mixed numbers',
    difficulty: {
      easy: 'Add two fractions with the same denominator.',
      medium:
        'Add or subtract two fractions with different denominators using a common denominator.',
      hard: 'Add or subtract mixed numbers with different denominators using a common denominator.',
    },
    expressionFor: ['easy', 'medium', 'hard'],
  },
  {
    id: 'g5_decimal_numbers',
    name: 'Decimal Numbers – Add & Subtract',
    icon: '🔣',
    grade: 5,
    color: '#FF9800',
    description: 'Tenths, hundredths, thousandths; reading, writing, comparing; add and subtract',
    difficulty: {
      easy: 'Add or subtract two tenths-place decimals.',
      medium: 'Add or subtract two hundredths-place decimals with regrouping.',
      hard: 'Add or subtract two thousandths-place decimals with regrouping; compare two decimals to determine which is larger.',
    },
    expressionFor: ['easy', 'medium', 'hard'],
  },
  {
    id: 'g5_fraction_decimal_conversion',
    name: 'Fraction ↔ Decimal Conversion',
    icon: '🔄',
    grade: 5,
    color: '#00BCD4',
    description: 'Converting between fractions and final decimals; comparing across forms',
    difficulty: {
      easy: 'Convert a common fraction (1/2, 1/4) to decimal.',
      medium: 'Convert a less common fraction (3/4, 3/5) to decimal.',
      hard: 'Compare a fraction and a decimal and state which is larger.',
    },
  },
  {
    id: 'g5_large_number_operations',
    name: 'Operations with Large Numbers',
    icon: '✖️',
    grade: 5,
    color: '#2196F3',
    description: 'Mental and written multiplication and division of multi-digit numbers',
    difficulty: {
      easy: '3-digit × 2-digit multiplication.',
      medium: '4-digit ÷ 2-digit division.',
      hard: 'Large-number addition, subtraction, multiplication, or division word problem.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g5_multi_step_word_problems',
    name: 'Multi-Step Word Problems',
    icon: '📖',
    grade: 5,
    color: '#F44336',
    description: 'Combining several operations and number types (whole, fraction, decimal)',
    difficulty: {
      easy: 'Two operations with whole numbers.',
      medium: 'One operation with fractions or decimals mixed with whole numbers.',
      hard: 'Sequential fraction reasoning (fraction of a fraction of a total).',
    },
  },
  {
    id: 'g5_roman_numbers',
    name: 'Roman Numbers',
    icon: '🏛️',
    grade: 5,
    color: '#795548',
    description: 'Reading and writing Roman numerals; converting between Roman and Arabic numerals',
    difficulty: {
      easy: 'Read or write a Roman numeral up to 20 (I–XX).',
      medium: 'Convert between Roman and Arabic numerals up to 100.',
      hard: 'Convert between Roman and Arabic numerals up to 1,000; apply subtractive notation (e.g., IV, IX, XL, XC).',
    },
  },
  {
    id: 'g5_geometry_polygons_area',
    name: 'Geometry – Area of Polygons',
    icon: '📐',
    grade: 5,
    color: '#E91E63',
    description:
      'Heights of triangles and parallelograms; area of triangles, parallelograms; composite shapes',
    difficulty: {
      easy: 'Area of a triangle (base × height ÷ 2).',
      medium: 'Area of a parallelogram (base × height).',
      hard: 'Area of a composite shape (rectangle + triangle).',
    },
  },
  {
    id: 'g5_averages',
    name: 'Averages',
    icon: '📊',
    grade: 5,
    color: '#607D8B',
    description: 'Calculating and interpreting the arithmetic mean of a data set',
    difficulty: {
      easy: 'Calculate the mean of three numbers.',
      medium: 'Calculate the mean of four numbers.',
      hard: 'Work backward from an average to find a missing data point.',
    },
  },

  // ── Grade 6 ──────────────────────────────────────────────────────────────────
  {
    id: 'g6_fractions_decimals_add_sub',
    name: 'Fractions & Decimals – Addition & Subtraction',
    icon: '🍕',
    grade: 6,
    color: '#9C27B0',
    description: 'Adding and subtracting fractions (including mixed numbers) and decimals',
    difficulty: {
      easy: 'Add or subtract two fractions with the same denominator.',
      medium:
        'Add or subtract two fractions with different denominators, or two decimals with regrouping.',
      hard: 'Add or subtract mixed numbers or a fraction and a decimal in a word-problem context.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g6_fractions_mul_div',
    name: 'Fractions – Multiplication & Division',
    icon: '✖️',
    grade: 6,
    color: '#E91E63',
    description: 'Multiplying and dividing fractions and mixed numbers',
    difficulty: {
      easy: 'Multiply or divide a fraction by a whole number.',
      medium: 'Multiply or divide two fractions or a fraction by a mixed number.',
      hard: 'Multiply or divide mixed numbers or a fraction and a decimal in a word-problem context.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g6_decimals_mul_div',
    name: 'Decimals – Multiplication & Division',
    icon: '🔣',
    grade: 6,
    color: '#FF9800',
    description: 'Multiplying and dividing decimals; decimal-point placement',
    difficulty: {
      easy: 'Multiply or divide a decimal by a whole number.',
      medium: 'Multiply or divide two decimals.',
      hard: 'Multiply or divide by a decimal in a measurement context.',
    },
    expressionFor: ['easy', 'medium'],
  },
  {
    id: 'g6_percentages',
    name: 'Percentages',
    icon: '💯',
    grade: 6,
    color: '#4CAF50',
    description:
      'Percent as part of 100; find part, find whole, find percent; link to fractions and decimals',
    difficulty: {
      easy: 'Find the part (10% of 80).',
      medium: 'Find the percentage (15 is what % of 60?).',
      hard: 'Find the whole given a part and its percentage (reverse percentage).',
    },
    expressionFor: ['easy'],
  },
  {
    id: 'g6_ratio_proportion',
    name: 'Ratio & Proportion',
    icon: '⚖️',
    grade: 6,
    color: '#2196F3',
    description: 'Ratio in problem-solving including direct proportion',
    difficulty: {
      easy: 'Simplify a ratio to its lowest terms.',
      medium: 'Solve a direct proportion (cost of N items).',
      hard: 'Multi-step ratio: find one part of a mixture given the total volume.',
    },
  },
  {
    id: 'g6_circles',
    name: 'Circles',
    icon: '⭕',
    grade: 6,
    color: '#E91E63',
    description: 'Circle properties: radius, diameter, circumference, and area',
    difficulty: {
      easy: 'Identify the radius or diameter of a circle given the other.',
      medium: 'Calculate the circumference of a circle given the radius (π ≈ 3.14).',
      hard: 'Calculate the area of a circle given the radius.',
    },
  },
  {
    id: 'g6_data_probability',
    name: 'Data, Averages & Probability',
    icon: '📊',
    grade: 6,
    color: '#607D8B',
    description: 'Mean, median, analyzing data; basic probability through chance events',
    difficulty: {
      easy: 'Calculate the mean of five numbers.',
      medium: 'Find the median of five numbers.',
      hard: 'Calculate a simple probability (marbles in a bag).',
    },
  },
  {
    id: 'g6_metric_system',
    name: 'Metric System',
    icon: '📏',
    grade: 6,
    color: '#00BCD4',
    description: 'Units of length (mm, cm, m, km) and mass (mg, g, kg); converting between units',
    difficulty: {
      easy: 'Convert between adjacent units (e.g., cm to m, g to kg).',
      medium: 'Convert between non-adjacent units (e.g., mm to m, mg to kg).',
      hard: 'Solve a word problem requiring unit conversion and arithmetic (e.g., total distance in km from measurements in m).',
    },
  },
];

export function getTopicsForGrade(grade: number): MathTopicConfig[] {
  return CURRICULUM_TOPICS.filter((t) => t.grade === grade);
}

export function getCurriculumTopicById(id: string): MathTopicConfig | undefined {
  return CURRICULUM_TOPICS.find((t) => t.id === id);
}
