import type { MathTopicConfig } from '@mathmagic/types';

export const CURRICULUM_TOPICS: MathTopicConfig[] = [
  // ── Grade 1 ──────────────────────────────────────────────────────────────────
  {
    id: 'g1_numbers_1_20',
    name: 'Numbers 1–20',
    icon: '🔢',
    grade: 1,
    color: '#4CAF50',
    description: 'Recognizing, reading, writing, and ordering numbers; counting forward/backward',
    difficulty: {
      easy: 'Numbers up to 10; identify or order a single number.',
      medium: 'Numbers up to 20; compare or order 2–3 numbers.',
      hard: 'Numbers up to 100; complete a sequence with a missing term.',
    },
  },
  {
    id: 'g1_addition_subtraction',
    name: 'Addition & Subtraction up to 20',
    icon: '➕',
    grade: 1,
    color: '#F44336',
    description: 'Basic addition and subtraction, including making 10 and counting on',
    difficulty: {
      easy: 'Within 10, no regrouping; straightforward "add together" or "take away".',
      medium: 'Within 20, with regrouping.',
      hard: 'Missing addend within 20; multi-step single-operation word problem.',
    },
  },
  {
    id: 'g1_odd_even',
    name: 'Odd & Even Numbers',
    icon: '🔄',
    grade: 1,
    color: '#9C27B0',
    description: 'Identifying odd and even numbers; recognizing simple parity patterns',
    difficulty: {
      easy: 'Classify a single number as odd or even.',
      medium: 'Count how many odd or even numbers exist within a range.',
      hard: 'Reason about parity in a real-world sharing context.',
    },
  },
  {
    id: 'g1_place_value',
    name: 'Place Value (Ones & Tens)',
    icon: '🏛️',
    grade: 1,
    color: '#FF9800',
    description: 'Understanding two-digit numbers as tens and ones; composing and decomposing',
    difficulty: {
      easy: 'Identify the tens or ones digit in a two-digit number.',
      medium: 'Compose or decompose a two-digit number into tens and ones.',
      hard: 'Recognise equivalent representations of a two-digit number.',
    },
  },
  {
    id: 'g1_word_problems',
    name: 'Word Problems',
    icon: '📖',
    grade: 1,
    color: '#2196F3',
    description: 'Single-step problems involving altogether, how many left, or comparing',
    difficulty: {
      easy: 'Simple "add together" with very small numbers (within 5).',
      medium: '"How many left" subtraction within 15.',
      hard: '"Find the difference" comparison between two quantities within 20.',
    },
  },
  {
    id: 'g1_2d_shapes',
    name: '2D Shapes',
    icon: '🔷',
    grade: 1,
    color: '#E91E63',
    description: 'Recognizing and naming basic shapes; identifying vertices, sides, and corners',
    difficulty: {
      easy: 'Name a shape when given a picture or description.',
      medium: 'Count sides or vertices of a named polygon.',
      hard: 'Identify a shape from a list of properties (side lengths, angles).',
    },
  },
  {
    id: 'g1_symmetry',
    name: 'Symmetry & Reflection',
    icon: '🪞',
    grade: 1,
    color: '#00BCD4',
    description: 'Intuitive understanding of slide and flip; recognizing symmetric shapes',
    difficulty: {
      easy: 'Identify whether a given shape or letter has a line of symmetry.',
      medium: 'Identify a shape or letter with a specific axis of symmetry.',
      hard: 'Count the total number of lines of symmetry in a regular polygon.',
    },
  },
  {
    id: 'g1_measurement',
    name: 'Measurement – Time & Length',
    icon: '⏰',
    grade: 1,
    color: '#607D8B',
    description: 'Reading clocks at whole hours; comparing lengths',
    difficulty: {
      easy: 'Read a clock showing a whole hour.',
      medium: 'Compare lengths of two or more objects.',
      hard: 'Calculate an end time given a start time and duration in whole hours.',
    },
  },

  // ── Grade 2 ──────────────────────────────────────────────────────────────────
  {
    id: 'g2_natural_numbers_1000',
    name: 'Natural Numbers up to 1,000',
    icon: '🔢',
    grade: 2,
    color: '#4CAF50',
    description: 'Reading, writing, comparing, and ordering numbers up to 1,000',
    difficulty: {
      easy: 'Compare two two-digit numbers.',
      medium: 'Order three three-digit numbers from smallest to largest.',
      hard: 'Identify a number from its hundreds, tens, and ones place values.',
    },
  },
  {
    id: 'g2_addition_subtraction',
    name: 'Addition & Subtraction up to 1,000',
    icon: '➕',
    grade: 2,
    color: '#F44336',
    description: 'Vertical and mental calculation including regrouping, up to 1,000',
    difficulty: {
      easy: 'Two-digit addition within 100, no regrouping.',
      medium: 'Two-digit addition with regrouping.',
      hard: 'Two-step problem within 1,000 (add then subtract or vice versa).',
    },
  },
  {
    id: 'g2_multiplication_intro',
    name: 'Introduction to Multiplication',
    icon: '✖️',
    grade: 2,
    color: '#2196F3',
    description: 'Multiplication as repeated addition and as rectangular arrays',
    difficulty: {
      easy: '×2, ×5, ×10 facts presented as equal groups.',
      medium: 'Other single-digit times-table facts (×3, ×4, ×6).',
      hard: 'Missing factor problem within single-digit tables.',
    },
  },
  {
    id: 'g2_division_intro',
    name: 'Introduction to Division',
    icon: '➗',
    grade: 2,
    color: '#FF9800',
    description: 'Division as inverse of multiplication and as fair sharing',
    difficulty: {
      easy: 'Simple equal-sharing within ×2/×5 tables.',
      medium: 'Find the number of equal groups within ×3/×4 tables.',
      hard: 'Word problem requiring interpretation of a division situation.',
    },
  },
  {
    id: 'g2_word_problems',
    name: 'Word Problems',
    icon: '📖',
    grade: 2,
    color: '#9C27B0',
    description: 'Multi-step word problems combining addition, subtraction, and multiplication',
    difficulty: {
      easy: 'One-step addition within 20.',
      medium: 'One-step multiplication context (equal groups).',
      hard: 'Two-step problem combining two different operations.',
    },
  },
  {
    id: 'g2_geometry_polygons',
    name: 'Geometry – Polygons',
    icon: '🔷',
    grade: 2,
    color: '#E91E63',
    description: 'Classifying triangles, quadrilaterals, and other polygons by sides and vertices',
    difficulty: {
      easy: 'Identify a polygon by its number of sides.',
      medium: 'Match a shape name to its number of sides.',
      hard: 'Identify a quadrilateral from a set of properties.',
    },
  },
  {
    id: 'g2_measurement_length_time',
    name: 'Measurement – Length & Time',
    icon: '📏',
    grade: 2,
    color: '#607D8B',
    description: 'Measuring in cm and m; reading half and quarter hours',
    difficulty: {
      easy: 'Read a clock showing a half hour.',
      medium: 'Compare or subtract two lengths in cm.',
      hard: 'Calculate a duration that crosses an hour boundary.',
    },
  },
  {
    id: 'g2_patterns',
    name: 'Patterns & Sequences',
    icon: '🔁',
    grade: 2,
    color: '#00BCD4',
    description: 'Identifying, continuing, and creating numerical patterns',
    difficulty: {
      easy: 'Continue a skip-counting sequence (by 2s).',
      medium: 'Continue a skip-counting sequence (by 5s).',
      hard: 'Fill in two missing terms in the middle of a sequence.',
    },
  },

  // ── Grade 3 ──────────────────────────────────────────────────────────────────
  {
    id: 'g3_natural_numbers_10000',
    name: 'Natural Numbers up to 10,000',
    icon: '🔢',
    grade: 3,
    color: '#4CAF50',
    description: 'Reading, writing, comparing 4-digit numbers; place value with thousands',
    difficulty: {
      easy: 'Read a 4-digit number in words.',
      medium: 'Compare two 4-digit numbers.',
      hard: 'Form the largest possible 4-digit number from given digits.',
    },
  },
  {
    id: 'g3_multiplication_table',
    name: 'Multiplication Table & Vertical Multiplication',
    icon: '✖️',
    grade: 3,
    color: '#2196F3',
    description: 'Mastery of all multiplication facts up to 10×10; 2-digit × 1-digit vertical',
    difficulty: {
      easy: 'Single multiplication fact within the 10×10 table.',
      medium: '2-digit × 1-digit vertical multiplication.',
      hard: 'Find the missing digit in a 2-digit × 1-digit product.',
    },
  },
  {
    id: 'g3_division_remainder',
    name: 'Division with Remainder',
    icon: '➗',
    grade: 3,
    color: '#FF9800',
    description: 'Division within tables, with and without remainder',
    difficulty: {
      easy: 'Exact division fact within the 10×10 table.',
      medium: 'Division with a remainder; state quotient and remainder.',
      hard: 'Word problem where the remainder must be interpreted (e.g., rounding up cars).',
    },
  },
  {
    id: 'g3_order_of_operations',
    name: 'Order of Operations',
    icon: '🧮',
    grade: 3,
    color: '#795548',
    description: 'Correct order of operations, including parentheses',
    difficulty: {
      easy: 'Two operations, no parentheses (multiplication before addition).',
      medium: 'Expression with parentheses.',
      hard: 'Translate a word description into the correct expression.',
    },
  },
  {
    id: 'g3_simple_fractions',
    name: 'Introduction to Fractions',
    icon: '🍕',
    grade: 3,
    color: '#9C27B0',
    description: 'Basic fractions (half, third, quarter, fifth) as parts of a whole or quantity',
    difficulty: {
      easy: 'Identify a fraction from a picture showing equal parts.',
      medium: 'Compare two unit fractions (e.g., 1/2 vs 1/3).',
      hard: 'Find a unit fraction of a quantity (e.g., 1/4 of 20).',
    },
  },
  {
    id: 'g3_two_step_word_problems',
    name: 'Two-Step Word Problems',
    icon: '📖',
    grade: 3,
    color: '#F44336',
    description: 'Problems requiring two calculation steps; emphasis on identifying the steps',
    difficulty: {
      easy: 'Same operation twice (add two equal amounts for two days).',
      medium: 'Two different operations (multiply then subtract).',
      hard: 'Multi-step with reasoning backward (work out an unknown component).',
    },
  },
  {
    id: 'g3_geometry_angles',
    name: 'Geometry – Angles & Shapes',
    icon: '📐',
    grade: 3,
    color: '#E91E63',
    description: 'Classifying angles (right, acute, obtuse), triangles, and quadrilaterals',
    difficulty: {
      easy: 'Classify a given angle as right, acute, or obtuse.',
      medium: 'Identify a triangle by its side lengths (equilateral, isosceles, scalene).',
      hard: 'Identify a quadrilateral from two given properties (e.g., 4 right angles, unequal sides).',
    },
  },
  {
    id: 'g3_measurement_units',
    name: 'Measurement – Units & Conversion',
    icon: '📏',
    grade: 3,
    color: '#607D8B',
    description: 'Measuring with appropriate units; converting between standard units',
    difficulty: {
      easy: 'State the number of grams in 1 kg or cm in 1 m.',
      medium: 'Convert between units (e.g., 3.5 m to cm).',
      hard: 'Word problem involving measurement with conversion.',
    },
  },
  {
    id: 'g3_data_bar_charts',
    name: 'Data – Bar Charts',
    icon: '📊',
    grade: 3,
    color: '#00BCD4',
    description: 'Collecting, organizing, representing, and interpreting data in bar charts',
    difficulty: {
      easy: 'Read a single value from a bar chart.',
      medium: 'Compare two values from a bar chart and find the difference.',
      hard: 'Compute the total of all values from a bar chart.',
    },
  },

  // ── Grade 4 ──────────────────────────────────────────────────────────────────
  {
    id: 'g4_large_numbers',
    name: 'Natural Numbers up to 1,000,000',
    icon: '🔢',
    grade: 4,
    color: '#4CAF50',
    description: 'Reading, writing, comparing, and rounding large numbers',
    difficulty: {
      easy: 'Write a 6-digit number from its word form.',
      medium: 'Round a 6-digit number to the nearest thousand.',
      hard: 'Estimate a sum of two large numbers to the nearest 10,000.',
    },
  },
  {
    id: 'g4_long_multiplication_division',
    name: 'Long Multiplication & Division',
    icon: '✖️',
    grade: 4,
    color: '#2196F3',
    description: 'Vertical multiplication with multi-digit factors; long division with 1- or 2-digit divisors',
    difficulty: {
      easy: '3-digit × 1-digit multiplication.',
      medium: '3-digit × 2-digit multiplication.',
      hard: 'Long division by a 2-digit divisor (exact).',
    },
  },
  {
    id: 'g4_properties_of_operations',
    name: 'Properties of Arithmetic',
    icon: '⚖️',
    grade: 4,
    color: '#795548',
    description: 'Commutative, associative, distributive properties; properties of zero and one',
    difficulty: {
      easy: 'Identify which property a given equation demonstrates.',
      medium: 'Apply the distributive property to rewrite a multiplication.',
      hard: 'Use properties strategically to compute a product mentally.',
    },
  },
  {
    id: 'g4_fractions_extended',
    name: 'Fractions – Extended Understanding',
    icon: '🍕',
    grade: 4,
    color: '#9C27B0',
    description: 'Equivalent fractions, comparing fractions, fractions greater than 1',
    difficulty: {
      easy: 'Determine whether two fractions are equivalent.',
      medium: 'Compare two fractions with different denominators.',
      hard: 'Find a non-unit fraction of a quantity (e.g., 2/3 of 24).',
    },
  },
  {
    id: 'g4_order_of_operations_advanced',
    name: 'Order of Operations (Advanced)',
    icon: '🧮',
    grade: 4,
    color: '#FF9800',
    description: 'Solving multi-step expressions following the conventional order, with parentheses',
    difficulty: {
      easy: 'Two operations — multiplication before addition.',
      medium: 'Multiple operations with parentheses.',
      hard: 'Match a word description to the correct algebraic expression.',
    },
  },
  {
    id: 'g4_perimeter_area',
    name: 'Geometry – Perimeter & Area',
    icon: '📐',
    grade: 4,
    color: '#E91E63',
    description: 'Perimeter and area of rectangles, squares, right triangles',
    difficulty: {
      easy: 'Calculate the perimeter of a rectangle.',
      medium: 'Calculate the area of a rectangle.',
      hard: 'Find a missing side length given the area and one dimension.',
    },
  },
  {
    id: 'g4_angles_degrees',
    name: 'Measurement – Angles in Degrees',
    icon: '📐',
    grade: 4,
    color: '#607D8B',
    description: 'Measuring and drawing angles with a protractor; classifying by size',
    difficulty: {
      easy: 'Classify an angle as acute, right, obtuse, or straight given its degree measure.',
      medium: 'State the definition or range of an acute angle.',
      hard: 'Find the missing angle on a straight line (supplementary angles).',
    },
  },
  {
    id: 'g4_multi_step_word_problems',
    name: 'Multi-Step Word Problems & Data',
    icon: '📖',
    grade: 4,
    color: '#F44336',
    description: 'Multi-step problems combining operations; reading double bar graphs and tables',
    difficulty: {
      easy: 'Two clear steps (multiply two prices then add totals).',
      medium: 'Three or more steps involving a fraction.',
      hard: 'Rate-based reasoning (pages per day, distance at speed).',
    },
  },

  // ── Grade 5 ──────────────────────────────────────────────────────────────────
  {
    id: 'g5_fractions_operations',
    name: 'Fractions – Addition & Subtraction',
    icon: '🍕',
    grade: 5,
    color: '#9C27B0',
    description: 'Equivalent/reduced fractions; adding and subtracting with same and different denominators; mixed numbers',
    difficulty: {
      easy: 'Add two fractions with the same denominator.',
      medium: 'Add two fractions with different denominators.',
      hard: 'Subtract mixed numbers in a word-problem context.',
    },
  },
  {
    id: 'g5_decimal_numbers',
    name: 'Decimal Numbers – Add & Subtract',
    icon: '🔣',
    grade: 5,
    color: '#FF9800',
    description: 'Tenths, hundredths, thousandths; reading, writing, comparing; add and subtract',
    difficulty: {
      easy: 'Add two tenths-place decimals.',
      medium: 'Add two hundredths-place decimals with regrouping.',
      hard: 'Multi-step word problem summing three decimal distances.',
    },
  },
  {
    id: 'g5_fraction_decimal_conversion',
    name: 'Fraction ↔ Decimal Conversion',
    icon: '🔄',
    grade: 5,
    color: '#00BCD4',
    description: 'Converting between fractions and decimals; comparing across forms',
    difficulty: {
      easy: 'Convert a common fraction (1/2, 1/4) to decimal.',
      medium: 'Convert a less common fraction (3/4, 3/5) to decimal.',
      hard: 'Compare a fraction and a decimal and state which is larger.',
    },
  },
  {
    id: 'g5_large_number_operations',
    name: 'Operations with Large Numbers',
    icon: '✖️',
    grade: 5,
    color: '#2196F3',
    description: 'Mental and written multiplication and division of multi-digit numbers',
    difficulty: {
      easy: '3-digit × 2-digit multiplication.',
      medium: '4-digit ÷ 2-digit division.',
      hard: 'Large-number multiplication word problem (daily production × days).',
    },
  },
  {
    id: 'g5_multi_step_word_problems',
    name: 'Multi-Step Word Problems',
    icon: '📖',
    grade: 5,
    color: '#F44336',
    description: 'Combining several operations and number types (whole, fraction, decimal)',
    difficulty: {
      easy: 'Two operations with whole numbers.',
      medium: 'One operation with fractions or decimals mixed with whole numbers.',
      hard: 'Sequential fraction reasoning (fraction of a fraction of a total).',
    },
  },
  {
    id: 'g5_geometry_polygons_area',
    name: 'Geometry – Area of Polygons',
    icon: '📐',
    grade: 5,
    color: '#E91E63',
    description: 'Heights of triangles and parallelograms; area of triangles, parallelograms; composite shapes',
    difficulty: {
      easy: 'Area of a triangle (base × height ÷ 2).',
      medium: 'Area of a parallelogram (base × height).',
      hard: 'Area of a composite shape (rectangle + triangle).',
    },
  },
  {
    id: 'g5_ratio_intro',
    name: 'Introduction to Ratio',
    icon: '⚖️',
    grade: 5,
    color: '#795548',
    description: 'Ratio as comparison between quantities; simple ratio problems',
    difficulty: {
      easy: 'Express a ratio in its simplest form.',
      medium: 'Share a quantity in a given ratio and find the larger share.',
      hard: 'Scale a recipe using proportional reasoning.',
    },
  },
  {
    id: 'g5_data_averages',
    name: 'Data – Averages & Double Bar Charts',
    icon: '📊',
    grade: 5,
    color: '#607D8B',
    description: 'Frequency tables, double bar charts, arithmetic mean',
    difficulty: {
      easy: 'Calculate the mean of three numbers.',
      medium: 'Calculate the mean of four numbers.',
      hard: 'Work backward from an average to find a missing data point.',
    },
  },

  // ── Grade 6 ──────────────────────────────────────────────────────────────────
  {
    id: 'g6_fractions_all_operations',
    name: 'Fractions – All Four Operations',
    icon: '🍕',
    grade: 6,
    color: '#9C27B0',
    description: 'Multiplication and division of fractions and mixed numbers',
    difficulty: {
      easy: 'Multiply a fraction by a whole number.',
      medium: 'Multiply two fractions.',
      hard: 'Divide by a fraction in a real-world context (servings from a total).',
    },
  },
  {
    id: 'g6_decimals_all_operations',
    name: 'Decimals – All Four Operations',
    icon: '🔣',
    grade: 6,
    color: '#FF9800',
    description: 'Multiplication and division of decimals; decimal-point placement',
    difficulty: {
      easy: 'Multiply a decimal by a whole number.',
      medium: 'Multiply two decimals.',
      hard: 'Divide by a decimal in a measurement context.',
    },
  },
  {
    id: 'g6_percentages',
    name: 'Percentages',
    icon: '💯',
    grade: 6,
    color: '#4CAF50',
    description: 'Percent as part of 100; find part, find whole, find percent; link to fractions and decimals',
    difficulty: {
      easy: 'Find the part (10% of 80).',
      medium: 'Find the percentage (15 is what % of 60?).',
      hard: 'Find the whole given a part and its percentage (reverse percentage).',
    },
  },
  {
    id: 'g6_ratio_proportion',
    name: 'Ratio & Proportion',
    icon: '⚖️',
    grade: 6,
    color: '#2196F3',
    description: 'Ratio in problem-solving including direct proportion',
    difficulty: {
      easy: 'Simplify a ratio to its lowest terms.',
      medium: 'Solve a direct proportion (cost of N items).',
      hard: 'Multi-step ratio: find one part of a mixture given the total volume.',
    },
  },
  {
    id: 'g6_advanced_geometry',
    name: 'Advanced Geometry – Polygons & Circle',
    icon: '📐',
    grade: 6,
    color: '#E91E63',
    description: 'Properties of quadrilaterals, diagonals, angles; area of trapezoids; circle (radius, diameter, circumference, area)',
    difficulty: {
      easy: 'Area of a trapezoid.',
      medium: 'Circumference of a circle given the radius (π ≈ 3.14).',
      hard: 'Area of a composite shape involving a circle inscribed in a square.',
    },
  },
  {
    id: 'g6_3d_solids_volume',
    name: '3D Solids – Volume & Nets',
    icon: '📦',
    grade: 6,
    color: '#795548',
    description: 'Identifying and constructing nets; volume of rectangular prisms',
    difficulty: {
      easy: 'Identify a solid from its net.',
      medium: 'Calculate the volume of a rectangular prism.',
      hard: 'Calculate the volume of water in a partially-filled tank in litres.',
    },
  },
  {
    id: 'g6_data_probability',
    name: 'Data, Averages & Probability',
    icon: '📊',
    grade: 6,
    color: '#607D8B',
    description: 'Mean, median, analyzing data; basic probability through chance events',
    difficulty: {
      easy: 'Calculate the mean of five numbers.',
      medium: 'Find the median of five numbers.',
      hard: 'Calculate a simple probability (marbles in a bag).',
    },
  },
  {
    id: 'g6_algebraic_thinking',
    name: 'Introduction to Algebraic Thinking',
    icon: '🔡',
    grade: 6,
    color: '#00BCD4',
    description: 'Patterns, simple algebraic expressions and equations, solving one-step equations',
    difficulty: {
      easy: 'Evaluate an expression for a given value of x.',
      medium: 'Solve a one-step equation (x + 7 = 15).',
      hard: 'Translate a word problem into an equation and solve it.',
    },
  },
];

export function getTopicsForGrade(grade: number): MathTopicConfig[] {
  return CURRICULUM_TOPICS.filter((t) => t.grade === grade);
}

export function getCurriculumTopicById(id: string): MathTopicConfig | undefined {
  return CURRICULUM_TOPICS.find((t) => t.id === id);
}
