export const TOPIC_NAMES: Record<string, string> = {
  // Grade 1
  g1_numbers_1_20: 'Numbers 1–20',
  g1_addition: 'Addition up to 20',
  g1_subtraction: 'Subtraction up to 20',
  g1_odd_even: 'Odd & Even Numbers',
  g1_place_value: 'Place Value (Ones & Tens)',
  g1_word_problems: 'Word Problems',
  g1_2d_shapes: '2D Shapes',
  g1_time_clock: 'Time & Clock',
  // Grade 2
  g2_natural_numbers_1000: 'Natural Numbers up to 1,000',
  g2_addition_subtraction: 'Addition & Subtraction up to 1,000',
  g2_multiplication_intro: 'Introduction to Multiplication',
  g2_division_intro: 'Introduction to Division',
  g2_word_problems: 'Word Problems',
  g2_geometry_polygons: 'Geometry – 3D Bodies & Shapes',
  g2_time_clock: 'Time & Clock',
  g2_patterns: 'Patterns & Sequences',
  // Grade 3
  g3_natural_numbers_10000: 'Natural Numbers up to 10,000',
  g3_addition_subtraction: 'Addition & Subtraction up to 10,000',
  g3_multiplication_table: 'Multiplication Table & Vertical Multiplication',
  g3_division_remainder: 'Division with Remainder',
  g3_order_of_operations: 'Order of Operations',
  g3_simple_fractions: 'Introduction to Fractions',
  g3_two_step_word_problems: 'Two-Step Word Problems',
  g3_measurement_units: 'Measurement – Units & Conversion',
  // Grade 4
  g4_large_numbers: 'Natural Numbers up to 1,000,000',
  g4_addition_subtraction: 'Addition & Subtraction',
  g4_long_multiplication_division: 'Long Multiplication & Division',
  g4_fractions_extended: 'Fractions – Extended Understanding',
  g4_order_of_operations_advanced: 'Order of Operations (Advanced)',
  g4_prime_composite_numbers: 'Prime & Composite Numbers',
  g4_perimeter_area: 'Geometry – Perimeter & Area',
  g4_multi_step_word_problems: 'Multi-Step Word Problems & Data',
  // Grade 5
  g5_fractions_operations: 'Fractions – Addition & Subtraction',
  g5_decimal_numbers: 'Decimal Numbers – Add & Subtract',
  g5_fraction_decimal_conversion: 'Fraction ↔ Decimal Conversion',
  g5_large_number_operations: 'Operations with Large Numbers',
  g5_multi_step_word_problems: 'Multi-Step Word Problems',
  g5_roman_numbers: 'Roman Numbers',
  g5_geometry_polygons_area: 'Geometry – Area of Polygons',
  g5_averages: 'Averages',
  // Grade 6
  g6_fractions_decimals_add_sub: 'Fractions & Decimals – Addition & Subtraction',
  g6_fractions_mul_div: 'Fractions – Multiplication & Division',
  g6_decimals_mul_div: 'Decimals – Multiplication & Division',
  g6_percentages: 'Percentages',
  g6_ratio_proportion: 'Ratio & Proportion',
  g6_circles: 'Circles',
  g6_data_probability: 'Data, Averages & Probability',
  g6_metric_system: 'Metric System',
};
